[package]
name = "rlnk"
version = "0.1.2"
edition = "2018"
description="create windows lnk file"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rlnk/"
readme = "README.md"
keywords = ["windows","lnk","shortcut"]
repository = "https://github.com/dobefore/rlnk.git"

[dependencies]
